### ISSUE TITLE
Speak() overwrites SpeechBase.Language to english when no language is given

### ISSUE THREAD

**Issue by corinnaj** [HassoPlattnerInstituteHCI/SpeechIOForUnity#1]
When using Speak() without providing a language parameter it will set the SpeechBase language to english, even If I set it to something else using SetLanguage() before.

**Comment by JotaroS** [comment]
A quick way of fixing would be to make a variable that indicates a current language, and to call `SetLanguage(current_language` every time at the beginning of `Speak()`.
