### ISSUE TITLE
Any way to avoid the commands dictionary and just straight transcribe the recognized speech?

### ISSUE THREAD

**Issue by STFUnity** [HassoPlattnerInstituteHCI/SpeechIOForUnity#11]
Hello, this works great but I don't need a narrowed down command list because I'm trying to use this to talk to chat AI and it will handle those things on its own. I just need the dictation to print every word I speak while it's listening instead of listening for Apple Banana and Orange.

Great setup but I didn't understand how to unbraid the commands dictionary from this otherwise facile tool of yours. Please let me know if there's a way to just print everything it hears until I say stop.

**Comment by JotaroS** [comment]
Hi @STFUnity,
We initially did not intend to use this plugin as dictation software. In addition, builtin OS Speech-To-Text only supports predefined set of words and thus this program is as well.
One way is to use cloud STT service, but that opposes the concept of this plugin works "right away", without any API accesses to external services.
